# Generated by Django 4.0 on 2022-01-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_alter_friendlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='timestamp',
        ),
    ]
